
#values read only from client with microservicea application name, when spring cloud dev profile is specified (DIFFERENT FROM SPRING BOOT PROFILE!)
config.currency.value=44.7
config.currency.name=EUR